### ISSUE TITLE
Files located in local texmf path are not determined correctly

### ISSUE THREAD

**Issue by martinKorp** [nlct/bib2gls#3]
If the .bib files of glossaries are placed in the local texmf path it seems that their path is not determined correctly. I.e., if we run `bib2gls` we get the following error message (`<tex file>` is a placeholder for the .tex file and `<bib file>` is a placeholder for the glossary .bib file):

```
bib2gls version 1.7 (2018-08-18)
Reading <tex file>.aux
Error: Illegal char <:> at index 4: c:\c:\Users\mkorp\texmf\bibtex\bib\<bib file>.bib
Transcript written to <tex file>.glg.
C:\texlive\2018\bin\win32\runscript.tlu:803: command failed with exit code 3:
java.exe -jar c:\texlive\2018\texmf-dist\scripts\bib2gls\bib2gls.jar "<tex file>"
```

Under Linux everything works perfectly. It seems to occur only under Windows.

**Comment by nlct** [comment]
It looks like the `c:\` drive part is being replicated for some reason. What do you get if you run `kpsewhich <bib file>.bib` from the command prompt?

**Comment by martinKorp** [comment]
If I run `kpsewhich <bib file>.bib` from the command prompt I get the correct path, i.e., `c:\Users\mkorp\texmf\bibtex\bib\<bib file>.bib`. As you indicated already it seems that `c:\` is for some reason added or duplicated.

**Comment by nlct** [comment]
If you have the [`testidx` package](https://ctan.org/pkg/testidx) installed the following MWE will also use `kpsewhich` to find the `.bib` files:
```latex
\documentclass{article}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[bib2gls]{testidx-glossaries}

\tstidxmakegloss

\begin{document}
\testidx
\tstidxprintglossaries
\end{document}
```
I'm guessing this will cause the same error. You can use that for testing if you like. Can you run `bib2gls` with `--debug` and check the transcript for the lines:
```
Running kpsewhich '<bib file>'
Processed returned: <path>
```
and the stack trace information (just the first `.bib` file information is sufficient) .

**Comment by martinKorp** [comment]
I have now setup the MWE and copied the necessary .bib files into my local texmf path. As expected I got the same error. Please find below the corresponding output (including the trace information):

```
Checking write access for C:\Projects\test.glstex
Initialising resource test.glstex.
File not found: testidx-glossaries-mathsym.bib
Running kpsewhich 'testidx-glossaries-mathsym.bib'
Processed returned: c:/Users/mkorp/texmf/bibtex/bib/testidx-glossaries-mathsym.bib
Error: Illegal char <:> at index 4: c:\c:\Users\mkorp\texmf\bibtex\bib\testidx-glossaries-mathsym.bib
java.nio.file.InvalidPathException: Illegal char <:> at index 4: c:\c:\Users\mkorp\texmf\bibtex\bib\testidx-glossaries-mathsym.bib
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.io.File.toPath(Unknown Source)
        at com.dickimawbooks.texparserlib.TeXPath.init(TeXPath.java:228)
        at com.dickimawbooks.texparserlib.TeXPath.<init>(TeXPath.java:51)
        at com.dickimawbooks.bib2gls.Bib2Gls.getBibFilePath(Bib2Gls.java:2674)
        at com.dickimawbooks.bib2gls.GlsResource.init(GlsResource.java:109)
        at com.dickimawbooks.bib2gls.GlsResource.<init>(GlsResource.java:53)
        at com.dickimawbooks.bib2gls.Bib2Gls.process(Bib2Gls.java:1722)
        at com.dickimawbooks.bib2gls.Bib2Gls.main(Bib2Gls.java:4336)
```

**Comment by nlct** [comment]
Thank you. I'll investigate and get it fixed.

**Comment by nlct** [comment]
This should hopefully now be fixed in version 1.8, which I've just uploaded to CTAN.

**Comment by martinKorp** [comment]
Thanks a lot for fixing the issue that fast. I have tested it quickly and it works now without any problems.

**Comment by M4nwe** [comment]
It seems, this kind of problem might have reoccurred in version 2.1 as the path to the local texfm is not determined correctly anymore on windows. This time, instead of duplicating the `c:\ ` part the first backslash in the path is missing. So I end up with: ` c:Users\...`

As suggested in this thread, I also ran bib2gls in debug mode getting a similar error:

```
bib2gls version 2.1 (2020-02-28)
...
Running kpsewhich 'greeksymbols.bib'
Processed returned: C:/Users/[...]/mytexmf/bibtex/bib/greeksymbols.bib
...
Parsing bib files for resource gls_test.glstex.
Default encoding: not set
Error: C:Users\[...]\mytexmf\bibtex\bib\greeksymbols.bib (The system cannot find the given path)
```

**Comment by nlct** [comment]
That's strange. I can't reproduce the problem. Here's a smaller example document:
```latex
\documentclass{report}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[record]{glossaries-extra}

\GlsXtrLoadResources[src=example-glossaries-brief,selection=all]

\begin{document}
\printunsrtglossary
\end{document}
```
I saved this as `test.tex` and ran `bib2gls --debug test` and the transcript file contained:
```
bib2gls version 2.1 (2020-02-28)
[...]
Running kpsewhich 'example-glossaries-brief.bib'
Processed returned: c:/texlive/2019/texmf-dist/bibtex/bib/glossaries-extra/example-glossaries-brief.bib
[...]
Checking read access for c:\texlive\2019\texmf-dist\bibtex\bib\glossaries-extra\example-glossaries-brief.bib
Reading c:\texlive\2019\texmf-dist\bibtex\bib\glossaries-extra\example-glossaries-brief.bib
```
This is with TeX Live 2019. The only noticeable difference between our transcript messages is the case of the drive letter (`c` for me and `C` for you). I'll investigate further.

**Comment by M4nwe** [comment]
Running your smaller example I still get that error. 
```
bib2gls version 2.1 (2020-02-28)
[...]
Running kpsewhich 'example-glossaries-brief.bib'
Processed returned: C:/Users/[...]/MiKTeX/2.9/bibtex/bib/glossaries-extra/example-glossaries-brief.bib
[...]
Checking read access for C:Users\[...]\MiKTeX\2.9\bibtex\bib\glossaries-extra\example-glossaries-brief.bib
Reading C:Users\[...]\MiKTeX\2.9\bibtex\bib\glossaries-extra\example-glossaries-brief.bib
```

This is with MiKTeX 2.9.

**Comment by nlct** [comment]
Can you try downloading [bib2gls.zip](https://github.com/nlct/bib2gls/files/4334735/bib2gls.zip) and testing it:

1. Unpack to a temporary directory. This should contain the files:
```
lib\bib2gls.jar
lib\convertgls2bib.jar
lib\texparserlib.jar
lib\resources\bib2gls-en.xml 
```
2. In the command prompt, cd to the directory with the test file and (assuming the test file is called `test.tex`) run:
```
java -jar path\to\lib\bib2gls.jar --debug test 
```
where `path\to\lib\bib2gls.jar` is the path to the `lib\bib2gls.jar` file that was unpacked from `bib2gls.zip`.

**Comment by M4nwe** [comment]
Looks like the fix works to me:
```
bib2gls version 2.1.20200315 (2020-03-15)
[...]
Running kpsewhich 'example-glossaries-brief.bib'
Processed returned: C:/Users/[...]/MiKTeX/2.9/bibtex/bib/glossaries-extra/example-glossaries-brief.bib
[...]
Checking read access for C:\Users\[...]\MiKTeX\2.9\bibtex\bib\glossaries-extra\example-glossaries-brief.bib
Reading C:\Users\[...]\MiKTeX\2.9\bibtex\bib\glossaries-extra\example-glossaries-brief.bib
```
Thank you very much for helping so fast.

**Comment by nlct** [comment]
Thank you for the feedback. I've uploaded bib2gls v2.2 to CTAN. It may take a few days to reach the TeX distributions.

**Comment by M4nwe** [comment]
The update has reached the MiKTeX distribution and the texmf path is determined correctly. Guess that means you can close this issue. Thanks again for the quick fix.

 

Von: Nicola Talbot [mailto:notifications@github.com] 
Gesendet: Montag, 16. März 2020 12:22
An: nlct/bib2gls <bib2gls@noreply.github.com>
Cc: M4nwe <j.steinmetz@tu-bs.de>; Comment <comment@noreply.github.com>
Betreff: Re: [nlct/bib2gls] Files located in local texmf path are not determined correctly (#3)

 

Thank you for the feedback. I've uploaded bib2gls v2.2 to CTAN. It may take a few days to reach the TeX distributions.

**Comment by nlct** [comment]
That's great. Thanks for the feedback.
